# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('img', models.CharField(default='', max_length=50, verbose_name='图片名称')),
            ],
        ),
    ]
